[package]
name = "web_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
chrono = "0.4.31"
dotenv = "0.15.0"
futures = "0.3.28"
sentry = "0.31.7"
sentry-actix = "0.31.7"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
