services:
    node:
        image: node:20-alpine
        command: sh -c "cd /var/www/html/ && npm run dev && tail -f /dev/null" # preventing it from stopping again
        volumes:
            - ./fe:/var/www/html
        working_dir: /var/www/html/
        ports:
            - '80'
        networks:
            default:
                aliases:
                    - rusty.docker
        environment:
            - VIRTUAL_HOST=.rusty.docker

    postgres:
        image: 'postgres:11.2'
        ports:
            - '5432:5432'
        environment:
            - 'POSTGRES_USER=username'
            - 'POSTGRES_DB=to_do'
            - 'POSTGRES_PASSWORD=password'
            - VIRTUAL_HOST=.pg-rusty.docker
        networks:
            default:
                aliases:
                    - pg-rusty.docker

    redis:
        image: 'redis:5.0.5'
        ports:
            - '6379:6379'
        networks:
            default:
                aliases:
                    - redis-rusty.docker
        environment:
            - VIRTUAL_HOST=.redis-rusty.docker