version: '2.4'
services:
    node:
        image: node:20-alpine
        command: sh -c "cd /var/www/html/ && tail -f /dev/null" # preventing it from stopping again
        volumes:
            - ./fe:/var/www/html
        working_dir: /var/www/html/
        ports:
            - '80'
        networks:
            default:
                aliases:
                    - rusty.docker
        environment:
            - VIRTUAL_HOST=.rusty.docker

volumes:
    code-node: