version: '2.4'
services:
    node:
        image: node:20-alpine
        command: sh -c "cd /var/www/html/ && yarn install && tail -f /dev/null" # preventing it from stopping again
        volumes:
            - code-node:/var/www/html
        working_dir: /var/www/html/

volumes:
    code-node: